### ISSUE TITLE
Ajout de sites sur lesquels faire des recherches

### ISSUE THREAD

**Issue by Cuchulain2612** [Cuchulain2612/dev2-Ephecom-2021-2022#1]
J'ai pour le moment créé la recherche sur Linkedin, YouTube et wikipedia. J'aimerais ajouter plusieurs autres sites. Je dois aussi prévoir le cas ou le site demande-é n'est pas trouvé/disponible.

**Comment by KeviinKeurvels** [comment]
Tu peux faire ça facilement avec un try except je pense 
Oublie pas que tu as une semaine pour faire ça donc tu as le temps :)
